name: replik
description: Replik - movie explorer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'   # <-- HATA BUNDAN GELİYORDU

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo/replik_logo_1024.png
    - assets/logo/replik_logo_256.png
    - assets/splash/splash.png

# Tam ekran web splash (arkaplan resmi + opsiyonel logo)
flutter_native_splash:
  web: true
  color: "#1a1a2e"
  color_dark: "#16213e"
  background_image: assets/splash/splash.png
  image: assets/logo/replik_logo_256.png
  image_dark: assets/logo/replik_logo_256.png
  image_size: 120
  image_dark_size: 120
  android_12:
    image: assets/logo/replik_logo_256.png
    icon_background_color: "#1a1a2e"
    image_dark: assets/logo/replik_logo_256.png
    icon_background_color_dark: "#16213e"
